### ISSUE TITLE
Bihar: Status variable

### ISSUE THREAD

**Issue by srishti-gupta-me** [tcpd/Urban-Local-Body#5]
_Status_ variable in all the rows for Bihar has been populated to '_Unknown_', wherever votes are available. 

_Status_ for these only needs to be '_Unknown_'
![image](https://user-images.githubusercontent.com/46262561/184288257-f098f669-0cfe-4c94-857e-4cedf508cda1.png)

**Comment by srishti-gupta-me** [comment]
Status for these updated to "Unknown"

![image](https://user-images.githubusercontent.com/46262561/179735643-2e49cf3e-cf97-4956-b0a0-77c229cb69cd.png)

**Comment by srishti-gupta-me** [comment]
Updated dataset: [primary.csv](https://github.com/tcpd/Urban_Local_Body/files/9274972/primary.csv)
1. Review the updated Bihar dataset. 
2. Cross-check with the codebook.

**Comment by zahir1509** [comment]
Patna Nagar Nigam - Ward 73, 74, 75 : Votes available yet marked status unknown.
Gaya - Nagar Panchayat Tekari - Ward 6 : Votes available yet marked status unknown.
Kishanganj - Nagar Panchayat Bahadurganj - Ward 13 : N_Cand = 1; Status = Uncontested.
Kishanganj - Nagar Parishad Kishanganj - Ward 5, 10 : N_Cand = 1; Status = Uncontested.
Muzaffarpur - Nagar Panchayat Motiput - Ward 6 : N_Cand = 1; Status = Uncontested.

Other instances of N_Cand = 1, Status unknown also present. 

Dataset has District Code, missing from codebook.

**Comment by srishti-gupta-me** [comment]
1. Codebook to be updated for the table (in the above screenshot) for the changes mentioned i.e. for _N_Cand_=1 where _Votes_ are blank/nan status is changed '_Uncontested_' from '_Unknown_'. If such a ward, is not available on the winner's list, _Notes_ are updated for these wards, as per the process.
2. In the case specific to Bihar, when _N_Cand_=1, but _Votes_ is not equal to NAN (np. nan/blank), then _Status_ is marked as '_Unknown_', this is done as the contesting candidate's data source had '_Uncontested_' specifically marked in the _ValidVotes_ column. 
3. _District_Code_ will not exist in the final dataset (compiled for all states), and will exist only in primary.csv.

**Comment by srishti-gupta-me** [comment]
Changes integrated and updated in the codebook v1.1.
